[package]
name = "vesti"
version = "0.0.9"
authors = ["Almagest <almagest0328@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = 'z'
panic = 'abort'

[dependencies]
structopt = "^0.3.21"
signal-hook = "0.3"
walkdir = "2.3"
unicode-width = "0.1.8"
bitflags = "1.2"
