[package]
name = "vesti"
version = "0.0.4"
authors = ["Almagest <almagest0328@gmail.com>"]
edition = "2018"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
structopt = "^0.3.21"
signal-hook = "0.3"
walkdir = "2.3"
