[package]
name = "vesti"
version = "0.7.0"
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
description = "A preprocessor that compiles into LaTeX"
repository = "https://github.com/e0328eric/vesti.git"
license = "MIT"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.27.0"
signal-hook = "0.3"
unicode-width = "0.1"
walkdir = "2.4"
