[package]
name = "vesti"
version = "0.16.0"
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
description = "A preprocessor that compiles into LaTeX"
repository = "https://codeberg.org/e0328eric/vesti.git"
license = "MIT"
edition = "2024"

[workspace]
members = ["vesti-macros"]

[profile.dev]
opt-level = 3
debug = true
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[features]
default = []
tectonic-backend = ["dep:tectonic"]

[dependencies]
vesti-macros = "0.1.0"
base64ct = { version = "1.6.0", features = ["alloc"] }
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
unicode-width = "0.2"
walkdir = "2.5"
yaml-rust = "0.4.5"
md-5 = "0.11"
dirs = "6"
libc = "0.2"
tectonic = { version = "0.16.9", optional = true }
ron = "0.12"
serde = { version = "1.0.214", features = ["derive"] }
unicode-segmentation = "1.13.2"
mlua = { version = "0.11.6", features = ["lua55", "vendored"] }
reqwest = { version = "0.13", features = ["blocking"] }
zip = "8"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = ["Win32_UI_WindowsAndMessaging"] }
