[package]
name = "vesti"
version = "0.2.2"
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
description = "A preprocessor that compiles into LaTeX"
license = "MIT"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 4
incremental = true
lto = true
opt-level = 3
panic = 'abort'
strip=true

[dependencies]
clap = { version = "3", features = ["derive"] }
signal-hook = "0.3"
walkdir = "2.3"
unicode-width = "0.1.8"
bitflags = "1.2"
