[package]
name = "vesti"
version = "0.0.3"
authors = ["Almagest <almagest0328@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies]
structopt = "^0.3.21"
signal-hook = "0.3.4"
