[package]
name = "vesti"
version = "0.3.3"
authors = ["Sungbae Jeong <almagest0328@gmail.com>"]
description = "A preprocessor that compiles into LaTeX"
license = "MIT"
edition = "2021"

[profile.dev]
opt-level = 0

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[dependencies]
clap = { version = "4", features = ["derive"] }
signal-hook = "0.3"
walkdir = "2.3"
unicode-width = "0.1.8"
