[package]
name = "vesti-tectonic"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.dev]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = "abort"
strip = true

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "e778080f0d8019247d332ef3a3df1202578ca202"
overlay-triplets-path = "dist/vcpkg-triplets"

[package.metadata.vcpkg.target]
x86_64-apple-darwin = { install = ["freetype", "harfbuzz[graphite2]", "icu"] }
aarch64-apple-darwin = { triplet = "arm64-osx", install = [
  "freetype",
  "harfbuzz[graphite2]",
  "icu",
] }
x86_64-unknown-linux-gnu = { install = [
  "fontconfig",
  "freetype",
  "harfbuzz[graphite2]",
  "icu",
] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-release", install = [
  "fontconfig",
  "freetype",
  "harfbuzz[graphite2]",
  "icu",
] }

[dependencies]
tectonic = { git = "https://github.com/tectonic-typesetting/tectonic.git", rev = "5e6babe320fe8f041a513b050e34f633006abad0", features = [
  "external-harfbuzz",
] }
