package main

// All dynamic arrays and owned Cow_Str values reachable from a Stmt belong to
// that statement.  Move statements rather than copying them, and finish them
// with stmt_deinit or stmt_list_deinit.

Stmt_List       :: [dynamic]Stmt
Cow_Str_List    :: [dynamic]Cow_Str
Use_Package_List :: [dynamic]Use_Package
Arg_List        :: [dynamic]Arg
Byte_Buffer     :: [dynamic]byte

Use_Package :: struct {
	name:    Cow_Str,
	options: Maybe(Cow_Str_List),
}

// Inverted storage preserves the Zig defaults (start/end are true) in Odin's
// zero value.  mid remains optional because null has distinct parser meaning.
Trim_Whitespace :: struct {
	keep_start_whitespace: bool,
	mid:                   Maybe(bool),
	keep_end_whitespace:   bool,
}

trim_whitespace_start :: proc(trim: Trim_Whitespace) -> bool {
	return !trim.keep_start_whitespace
}

trim_whitespace_end :: proc(trim: Trim_Whitespace) -> bool {
	return !trim.keep_end_whitespace
}

Math_State :: enum u8 {
	Inline,
	Display,
	Labeled,
}

Delimiter_Kind :: enum u8 {
	None,
	Left_Big,
	Right_Big,
}

Arg_Need :: enum u8 {
	Main_Arg,
	Optional,
	Star_Arg,
}

Arg :: struct {
	needed: Arg_Need,
	ctx:    Stmt_List,
}

Nop_Stmt         :: struct {}
Placeholder_Stmt :: struct {}

Text_Lit_Stmt :: struct {
	text: Cow_Str,
}

// Math literals and delimiter spellings borrow slices from source/static data.
Math_Lit_Stmt :: struct {
	text: string,
}

Math_Ctx_Stmt :: struct {
	state: Math_State,
	inner: Stmt_List,
	label: Maybe(Byte_Buffer),
}

Braced_Stmt :: struct {
	unwrap_brace: bool,
	inner:        Stmt_List,
}

Fraction_Stmt :: struct {
	numerator:   Stmt_List,
	denominator: Stmt_List,
}

Document_Start_Stmt :: struct {}
Document_End_Stmt   :: struct {}

Document_Class_Stmt :: struct {
	name:    Cow_Str,
	options: Maybe(Cow_Str_List),
}

Import_Single_Pkg_Stmt :: struct {
	pkg: Use_Package,
}

Import_Multiple_Pkgs_Stmt :: struct {
	packages: Use_Package_List,
}

Import_Vesti_Stmt :: struct {
	name: Byte_Buffer,
}

Plain_Text_In_Math_Stmt :: struct {
	add_front_space: bool,
	add_back_space:  bool,
	inner:           Stmt_List,
}

Math_Delimiter_Stmt :: struct {
	delimiter: string,
	kind:      Delimiter_Kind,
}

Defun_Param_List_Stmt :: struct {
	// nested=0 emits #, nested=1 emits ##, nested=2 emits ####, and so on.
	nested:  uint,
	arg_num: uint,
	span:    Span,
}

Define_Function_Stmt :: struct {
	name:      Cow_Str,
	param_str: Maybe(Cow_Str),
	kind:      Defun_Kind,
	inner:     Stmt_List,
}

Define_Env_Stmt :: struct {
	name:        Cow_Str,
	param_str:   Maybe(Cow_Str),
	kind:        Defenv_Kind,
	inner_begin: Stmt_List,
	inner_end:   Stmt_List,
}

Environment_Stmt :: struct {
	name:  Cow_Str,
	args:  Arg_List,
	inner: Stmt_List,
	label: Maybe(Byte_Buffer),
}

// Generated by the #picture builtin.  unit_length is absent when codegen
// should use its baked-in default.
Picture_Environment_Stmt :: struct {
	width:       uint,
	height:      uint,
	xoffset:     Maybe(uint),
	yoffset:     Maybe(uint),
	unit_length: Maybe(Byte_Buffer),
	inner:       Stmt_List,
}

Begin_Phantom_Environ_Stmt :: struct {
	name:        Cow_Str,
	args:        Arg_List,
	add_newline: bool,
}

End_Phantom_Environ_Stmt :: struct {
	name: Cow_Str,
}

File_Path_Stmt :: struct {
	path: Cow_Str,
}

Lua_Code_Stmt :: struct {
	code_span:   Span,
	is_global:   bool,
	// The array backing is owned; each string element borrows source storage.
	code_import: Maybe([dynamic]string),
	code_export: Maybe(string),
	code:        Byte_Buffer,
}

// Stmt is a closed, non-nil tagged union.  Parsers construct it by converting
// a payload (for example Stmt(Text_Lit_Stmt{...})); consumers use a type switch.
Stmt :: union #no_nil {
	Nop_Stmt,
	Placeholder_Stmt,
	Text_Lit_Stmt,
	Math_Lit_Stmt,
	Math_Ctx_Stmt,
	Braced_Stmt,
	Fraction_Stmt,
	Document_Start_Stmt,
	Document_End_Stmt,
	Document_Class_Stmt,
	Import_Single_Pkg_Stmt,
	Import_Multiple_Pkgs_Stmt,
	Import_Vesti_Stmt,
	Plain_Text_In_Math_Stmt,
	Math_Delimiter_Stmt,
	Defun_Param_List_Stmt,
	Define_Function_Stmt,
	Define_Env_Stmt,
	Environment_Stmt,
	Picture_Environment_Stmt,
	Begin_Phantom_Environ_Stmt,
	End_Phantom_Environ_Stmt,
	File_Path_Stmt,
	Lua_Code_Stmt,
}

byte_buffer_deinit :: proc(buffer: ^Byte_Buffer, allocator := context.allocator) {
	_ = allocator // Kept for a uniform ownership-helper API; arrays remember it.
	if buffer == nil {
		return
	}
	if buffer^ != nil {
		delete(buffer^)
	}
	buffer^ = nil
}

cow_str_list_deinit :: proc(values: ^Cow_Str_List, allocator := context.allocator) {
	if values == nil {
		return
	}
	for &value in values^ {
		cow_str_deinit(&value, allocator)
	}
	if values^ != nil {
		delete(values^)
	}
	values^ = nil
}

use_package_deinit :: proc(pkg: ^Use_Package, allocator := context.allocator) {
	if pkg == nil {
		return
	}
	cow_str_deinit(&pkg.name, allocator)
	if options, ok := pkg.options.?; ok {
		cow_str_list_deinit(&options, allocator)
		pkg.options = nil
	}
}

use_package_list_deinit :: proc(packages: ^Use_Package_List, allocator := context.allocator) {
	if packages == nil {
		return
	}
	for &pkg in packages^ {
		use_package_deinit(&pkg, allocator)
	}
	if packages^ != nil {
		delete(packages^)
	}
	packages^ = nil
}

arg_deinit :: proc(arg: ^Arg, allocator := context.allocator) {
	if arg == nil {
		return
	}
	stmt_list_deinit(&arg.ctx, allocator)
}

arg_list_deinit :: proc(args: ^Arg_List, allocator := context.allocator) {
	if args == nil {
		return
	}
	for &arg in args^ {
		arg_deinit(&arg, allocator)
	}
	if args^ != nil {
		delete(args^)
	}
	args^ = nil
}

stmt_list_deinit :: proc(stmts: ^Stmt_List, allocator := context.allocator) {
	if stmts == nil {
		return
	}
	for &stmt in stmts^ {
		stmt_deinit(&stmt, allocator)
	}
	if stmts^ != nil {
		delete(stmts^)
	}
	stmts^ = nil
}

// stmt_deinit recursively releases every allocation owned by a statement and
// resets it to Nop_Stmt, making repeated cleanup safe.
stmt_deinit :: proc(stmt: ^Stmt, allocator := context.allocator) {
	if stmt == nil {
		return
	}

	switch &value in stmt^ {
	case Nop_Stmt, Placeholder_Stmt, Math_Lit_Stmt,
	     Document_Start_Stmt, Document_End_Stmt, Math_Delimiter_Stmt,
	     Defun_Param_List_Stmt:
		// These variants contain no owned storage.
	case Text_Lit_Stmt:
		cow_str_deinit(&value.text, allocator)
	case Math_Ctx_Stmt:
		stmt_list_deinit(&value.inner, allocator)
		if label, ok := value.label.?; ok {
			byte_buffer_deinit(&label, allocator)
			value.label = nil
		}
	case Braced_Stmt:
		stmt_list_deinit(&value.inner, allocator)
	case Fraction_Stmt:
		stmt_list_deinit(&value.numerator, allocator)
		stmt_list_deinit(&value.denominator, allocator)
	case Document_Class_Stmt:
		cow_str_deinit(&value.name, allocator)
		if options, ok := value.options.?; ok {
			cow_str_list_deinit(&options, allocator)
			value.options = nil
		}
	case Import_Single_Pkg_Stmt:
		use_package_deinit(&value.pkg, allocator)
	case Import_Multiple_Pkgs_Stmt:
		use_package_list_deinit(&value.packages, allocator)
	case Import_Vesti_Stmt:
		byte_buffer_deinit(&value.name, allocator)
	case Plain_Text_In_Math_Stmt:
		stmt_list_deinit(&value.inner, allocator)
	case Define_Function_Stmt:
		cow_str_deinit(&value.name, allocator)
		if param_str, ok := value.param_str.?; ok {
			cow_str_deinit(&param_str, allocator)
			value.param_str = nil
		}
		stmt_list_deinit(&value.inner, allocator)
	case Define_Env_Stmt:
		cow_str_deinit(&value.name, allocator)
		if param_str, ok := value.param_str.?; ok {
			cow_str_deinit(&param_str, allocator)
			value.param_str = nil
		}
		stmt_list_deinit(&value.inner_begin, allocator)
		stmt_list_deinit(&value.inner_end, allocator)
	case Environment_Stmt:
		cow_str_deinit(&value.name, allocator)
		arg_list_deinit(&value.args, allocator)
		stmt_list_deinit(&value.inner, allocator)
		if label, ok := value.label.?; ok {
			byte_buffer_deinit(&label, allocator)
			value.label = nil
		}
	case Picture_Environment_Stmt:
		if unit_length, ok := value.unit_length.?; ok {
			byte_buffer_deinit(&unit_length, allocator)
			value.unit_length = nil
		}
		stmt_list_deinit(&value.inner, allocator)
	case Begin_Phantom_Environ_Stmt:
		cow_str_deinit(&value.name, allocator)
		arg_list_deinit(&value.args, allocator)
	case End_Phantom_Environ_Stmt:
		cow_str_deinit(&value.name, allocator)
	case File_Path_Stmt:
		cow_str_deinit(&value.path, allocator)
	case Lua_Code_Stmt:
		if imports, ok := value.code_import.?; ok {
			if imports != nil {
				delete(imports)
			}
			value.code_import = nil
		}
		byte_buffer_deinit(&value.code, allocator)
	}

	stmt^ = Nop_Stmt{}
}
