package main

import "core:fmt"
import "core:mem"
import "core:os"
import "core:path/filepath"
import "core:strings"

Compiler_Request :: struct {
	main_filename:  string,
	engine:         ^Latex_Engine,
	compile_limit:  int,
	compile_all:    bool,
	emit_tex:       bool,
	before_script:  string,
	step_script:    string,
	dummy_directory: string,
	lua_runtime:    ^Lua_Runtime,
	diagnostic:     ^Diagnostic,
	allocator:      mem.Allocator,
}

compiler_request_default :: proc(
	main_filename: string,
	engine: ^Latex_Engine,
	diagnostic: ^Diagnostic,
	allocator: mem.Allocator = context.allocator,
) -> Compiler_Request {
	return Compiler_Request{
		main_filename   = main_filename,
		engine          = engine,
		compile_limit   = 3,
		before_script   = "before.lua",
		step_script     = "step.lua",
		dummy_directory = VESTI_DUMMY_DIR,
		diagnostic      = diagnostic,
		allocator       = allocator,
	}
}

compiler_error :: proc(request: ^Compiler_Request, message: string, note := "") -> bool {
	if request.diagnostic != nil {
		_ = diagnostic_set(request.diagnostic, .IO, message, {}, false, note)
	}
	return false
}

compiler_prepare_output_directory :: proc(request: ^Compiler_Request) -> bool {
	if err := os.make_directory_all(request.dummy_directory); err != nil {
		return compiler_error(request, "cannot create the Vesti output directory")
	}
	ignore_path, join_err := filepath.join(
		{request.dummy_directory, ".gitignore"},
		request.allocator,
	)
	if join_err != nil {
		return compiler_error(request, "cannot construct the output .gitignore path")
	}
	defer delete(ignore_path, request.allocator)
	if err := os.write_entire_file(ignore_path, "*\n"); err != nil {
		return compiler_error(request, "cannot write the output .gitignore")
	}
	return true
}

compiler_tex_prologue :: proc(output: ^strings.Builder, engine: Latex_Engine) {
	_ = fmt.sbprintf(
		output,
		"%%\n" +
		"%%    this file was generated by vesti %s\n" +
		"%%    compile this file using %s engine\n" +
		"%%    =========================================\n" +
		"%%    vesti: https://github.com/e0328eric/vesti\n" +
		"%%\n",
		VESTI_VERSION,
		latex_engine_string(engine),
	)
}

compiler_parse_and_codegen :: proc(
	source: string,
	filename: string,
	base_directory: string,
	is_main: bool,
	engine: ^Latex_Engine,
	diagnostic: ^Diagnostic,
	output: ^strings.Builder,
	allocator: mem.Allocator,
	lua_runtime: ^Lua_Runtime = nil,
	dummy_directory := VESTI_DUMMY_DIR,
	perform_file_operations := true,
	allow_engine_change := true,
) -> bool {
	preprocessor, init_err := preprocessor_init(
		source,
		base_directory,
		diagnostic,
		allocator,
	)
	if init_err != nil {
		if diagnostic != nil {
			_ = diagnostic_set(diagnostic, .Parse, "cannot initialize the preprocessor")
		}
		return false
	}
	defer preprocessor_deinit(&preprocessor)
	tokens, preprocess_ok := preprocessor_process(&preprocessor)
	if !preprocess_ok {
		return false
	}
	defer token_list_deinit(&tokens, allocator)

	options := parser_options_default(allocator)
	options.diagnostic = diagnostic
	options.allow_lua_code = lua_runtime != nil
	options.allow_global_definition = true
	options.is_main = is_main
	options.allow_engine_change = allow_engine_change
	options.engine = engine
	if engine != nil {
		options.current_engine = engine^
	}
	options.file_directory = base_directory
	options.dummy_directory = dummy_directory
	options.perform_file_operations = perform_file_operations
	ast, parse_ok := parser_parse(tokens.items[:], options)
	if !parse_ok {
		return false
	}
	defer stmt_list_deinit(&ast, allocator)
	if lua_runtime != nil && engine != nil {
		lua_runtime.engine = engine^
	}

	evaluator: Codegen_Lua_Evaluator
	user_data: rawptr
	if lua_runtime != nil {
		evaluator = lua_codegen_evaluate
		user_data = lua_runtime
	}
	generator := codegen_init(
		allocator,
		source,
		ast[:],
		is_main,
		diagnostic,
		evaluator,
		user_data,
	)
	defer codegen_deinit(&generator)
	return codegen_emit(&generator, nil, output)
}

compiler_emit_vesti_file :: proc(
	request: ^Compiler_Request,
	filename: string,
	is_main: bool,
) -> bool {
	bytes, read_err := os.read_entire_file(filename, request.allocator)
	if read_err != nil {
		if request.diagnostic != nil {
			_ = diagnostic_setf(
				request.diagnostic,
				.IO,
				{},
				false,
				"",
				"failed to open file `%s`",
				filename,
			)
		}
		return false
	}
	defer delete(bytes, request.allocator)
	source := string(bytes)
	if request.diagnostic != nil &&
	   !diagnostic_set_metadata(request.diagnostic, filename, source) {
		return compiler_error(request, "out of memory recording diagnostic metadata")
	}

	base_directory := filepath.dir(filename)
	body := strings.builder_make(allocator = request.allocator)
	defer strings.builder_destroy(&body)
	if !compiler_parse_and_codegen(
		source,
		filename,
		base_directory,
		is_main,
		request.engine,
		request.diagnostic,
		&body,
		request.allocator,
		request.lua_runtime,
		request.dummy_directory,
		true,
		true,
	) {
		return false
	}

	tex_filename, name_ok := generated_tex_filename(filename, is_main, request.allocator)
	if !name_ok {
		return compiler_error(request, "cannot construct the generated TeX filename")
	}
	defer delete(tex_filename, request.allocator)
	output_path, join_err := filepath.join(
		{request.dummy_directory, tex_filename},
		request.allocator,
	)
	if join_err != nil {
		return compiler_error(request, "cannot construct the generated TeX path")
	}
	defer delete(output_path, request.allocator)

	output := strings.builder_make(allocator = request.allocator)
	defer strings.builder_destroy(&output)
	compiler_tex_prologue(&output, request.engine^)
	_ = strings.write_string(&output, strings.to_string(body))
	if write_err := os.write_entire_file(output_path, strings.to_string(output)); write_err != nil {
		return compiler_error(request, "cannot write generated TeX", output_path)
	}
	return true
}

compiler_path_is_main :: proc(left, right: string) -> bool {
	return os.are_paths_identical(left, right)
}

compiler_compile_backend :: proc(request: ^Compiler_Request, main_absolute: string) -> bool {
	tex_filename, tex_ok := generated_tex_filename(main_absolute, true, request.allocator)
	if !tex_ok {
		return compiler_error(request, "cannot construct the main TeX filename")
	}
	defer delete(tex_filename, request.allocator)

	if request.engine^ == .tectonic {
		if !run_latex_engine(
			request.engine^,
			tex_filename,
			request.dummy_directory,
			request.compile_limit,
			request.diagnostic,
			request.allocator,
		) {
			return false
		}
	} else {
		for _ in 0 ..< request.compile_limit {
			if !run_latex_engine(
				request.engine^,
				tex_filename,
				request.dummy_directory,
				1,
				request.diagnostic,
				request.allocator,
			) {
				return false
			}
			if request.lua_runtime != nil && len(request.step_script) > 0 &&
			   !lua_runtime_run_file(request.lua_runtime, request.step_script, false) {
				return false
			}
		}
	}

	pdf_filename, pdf_ok := generated_pdf_filename(main_absolute, request.allocator)
	if !pdf_ok {
		return compiler_error(request, "cannot construct the generated PDF filename")
	}
	defer delete(pdf_filename, request.allocator)
	pdf_source, join_err := filepath.join(
		{request.dummy_directory, pdf_filename},
		request.allocator,
	)
	if join_err != nil {
		return compiler_error(request, "cannot construct the generated PDF path")
	}
	defer delete(pdf_source, request.allocator)
	if copy_err := os.copy_file(pdf_filename, pdf_source); copy_err != nil {
		return compiler_error(request, "cannot copy the generated PDF", pdf_source)
	}
	return true
}

compiler_compile_once :: proc(request: ^Compiler_Request) -> bool {
	if request == nil || request.engine == nil || request.diagnostic == nil {
		return false
	}
	if request.allocator.procedure == nil {
		request.allocator = context.allocator
	}
	if request.compile_limit < 1 {
		return compiler_error(request, "compile limit must be positive")
	}
	if len(request.dummy_directory) == 0 {
		request.dummy_directory = VESTI_DUMMY_DIR
	}
	if !vesti_extension_is_valid(request.main_filename) {
		return compiler_error(request, "main input must have the .ves extension")
	}
	main_absolute, absolute_err := filepath.abs(request.main_filename, request.allocator)
	if absolute_err != nil || !os.is_file(main_absolute) {
		if absolute_err == nil {
			delete(main_absolute, request.allocator)
		}
		return compiler_error(request, "failed to open the main Vesti file", request.main_filename)
	}
	defer delete(main_absolute, request.allocator)

	if !compiler_prepare_output_directory(request) {
		return false
	}
	if request.lua_runtime != nil && len(request.before_script) > 0 &&
	   !lua_runtime_run_file(request.lua_runtime, request.before_script, false) {
		return false
	}

	if !compiler_emit_vesti_file(request, main_absolute, true) {
		return false
	}
	if request.compile_all {
		files, discovered := discover_vesti_files(".", request.allocator)
		if !discovered {
			return compiler_error(request, "failed to discover Vesti source files")
		}
		defer compiler_path_list_deinit(&files, request.allocator)
		for filename in files {
			if compiler_path_is_main(filename, main_absolute) {
				continue
			}
			if !compiler_emit_vesti_file(request, filename, false) {
				return false
			}
		}
	}

	if request.emit_tex {
		return true
	}
	return compiler_compile_backend(request, main_absolute)
}

// Callback used by vesti.parse inside Lua.  It intentionally disables nested
// Lua execution, engine changes, module copies, and other file mutations.
compiler_lua_parse :: proc(
	source: string,
	output: ^strings.Builder,
	user_data: rawptr,
) -> bool {
	runtime := (^Lua_Runtime)(user_data)
	if runtime == nil {
		return false
	}
	engine := runtime.engine
	if runtime.diagnostic != nil {
		_ = diagnostic_set_metadata(runtime.diagnostic, "<luacode>", source)
	}
	return compiler_parse_and_codegen(
		source,
		"<luacode>",
		".",
		false,
		&engine,
		runtime.diagnostic,
		output,
		runtime.allocator,
		nil,
		VESTI_DUMMY_DIR,
		false,
		false,
	)
}
